# Generated by Django 4.0.3 on 2022-04-10 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(default='#070707', max_length=7, validators=[django.core.validators.RegexValidator(code='hex_regex', message='color must be in this format #xxxxxx', regex='^#([0-9a-fA-F]{2}){3}$')])),
                ('balance', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoices',
                'managed': True,
            },
        ),
    ]
