services:
  # Postgres - database
  db:
    image: postgres:14.2-alpine
    healthcheck:
      test: pg_isready -d bahoodb -U bahoodbadmin
      interval: 5s
      timeout: 10s
      retries: 6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bahoodb
      - POSTGRES_USER=bahoodbadmin
      - POSTGRES_PASSWORD=bahoodbpassword
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  # Adminer - database managemer
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  # Django - backend
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: --migrate python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DB_NAME=bahoodb
      - DB_USER=bahoodbadmin
      - DB_PASSWORD=bahoodbpassword
      - DB_HOST=db
      - DB_PORT=5432
      - TIME_ZONE=Asia/Tehran
      - GHASEDAK_API_KEY_FILE=/run/secrets/BAHOO_GHASEDAK_API_KEY 
      - SECRET_KEY_FILE=/run/secrets/BAHOO_SECRET_KEY
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - BAHOO_GHASEDAK_API_KEY
      - BAHOO_SECRET_KEY
    networks:
      - backend

secrets:
  BAHOO_GHASEDAK_API_KEY:
    file: secrets/BAHOO_GHASEDAK_API_KEY
  BAHOO_SECRET_KEY:
    file: secrets/BAHOO_SECRET_KEY

volumes:
  dbdata:

networks:
  backend:
