# Generated by Django 4.0.3 on 2022-05-11 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=32)),
                ('icon', models.CharField(default='i000000', max_length=7, validators=[django.core.validators.RegexValidator(code='hex_regex', message='color must be in this format #xxxxxx', regex='^i[0-9]{6}$')])),
                ('color', models.CharField(default='#070707', max_length=7, validators=[django.core.validators.RegexValidator(code='hex_regex', message='color must be in this format #xxxxxx', regex='^#([0-9a-fA-F]{2}){3}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='invoice.invoice')),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
    ]
