# Generated by Django 4.0.3 on 2022-05-14 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_remove_tag_update_at_tag_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.CharField(default='i000000', max_length=7, validators=[django.core.validators.RegexValidator(code='icon_regex', message='icon must be in this format ixxxxxx', regex='^i[0-9]{6}$')]),
        ),
    ]
